spring:
  config:
    import:
      - optional:classpath:./secret/db.yml
  application:
    name: spring_basic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
#    database-platform: org.hibernate.dialect.MariaDBDialect